<a href="https://colab.research.google.com/github/MarconeRafael/Modulos_Comuns_no_TensorFLow_2/blob/main/M%C3%B3dulos_Comuns_no_TensorFLow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# 2. Módulos Comuns no TensorFlow 2

## 2.1 Construindo Modelos Sequenciais - .Sequential()

A maneira mais comum de construir um modelo é empilhar camadas usando **tf.keras.Sequential**.



In [2]:
modelo = tf.keras.Sequential()

modelo.add(tf.keras.layers.Dense(32, activation='relu'))
modelo.add(tf.keras.layers.Dense(32, activation='relu'))
modelo.add(tf.keras.layers.Dense(10, activation='relu'))

modelo

## 2.1.1 Construindo um Modelo Funcional - .Model()

Os modelos funcionais são construídos principalmente usando **tf.keras.Input** e **tf.keras.Model**, que são mais complexos que **tf.keras.Sequential**, mas têm um bom efeito. As variáveis podem ser inseridas ao mesmo tempo ou em diferentes fases, e os dados podem ser emitidos em diferentes fases. Modelos funcionais são preferidos se mais de uma saída de modelo for necessária.

**.Sequential vs .Model**:
O modelo tf.keras.Sequential é uma pilha simples de camadas que não pode representar modelos arbitrários. Você pode usar a API funcional Keras (i.e., .Model) para construir topologias de modelos complexos, por exemplo:
* Modelos multi-entrada
* Modelos de múltiplas saídas
* Modelos com camadas compartilhadas
* Modelos com fluxos de dados não sequenciais (por exemplo, conexões residuais)

In [3]:
entrada  = tf.keras.Input(shape=(32,))
camada_1 = tf.keras.layers.Dense(32, activation='relu')(entrada)
camada_2 = tf.keras.layers.Dense(32, activation='relu')(camada_1)
saida    = tf.keras.layers.Dense(10, activation='softmax')(camada_2)

modelo_2 = tf.keras.models.Model(entrada, saida)
# Print modelo
modelo_2.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 32)]              0         
                                                                 
 dense_3 (Dense)             (None, 32)                1056      
                                                                 
 dense_4 (Dense)             (None, 32)                1056      
                                                                 
 dense_5 (Dense)             (None, 10)                330       
                                                                 
Total params: 2442 (9.54 KB)
Trainable params: 2442 (9.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


## 2.2 Camadas Disponíveis

O módulo **tf.keras.layers** é usado para configurar as camadas da rede neural. As classes comuns incluem:

* **tf.keras.layers.Dense**: constrói uma camada totalmente conectada.
* **tf.keras.layers.Conv2D**: constrói uma camada convolucional bidimensional.
* **tf.keras.layers.MaxPooling2D/AveragePooling2D**: constrói uma camada de agrupamento máximo/médio.
* **tf.keras.layers.RNN**: Constrói uma camada de rede neural recorrente.
* **tf.keras.layers.LSTM**: constrói uma camada de rede LSTM/unidade LSTM.
* **tf.keras.layers.GRU**: constrói uma unidade GRU/camada de rede GRU.
* **tf.keras.layers.Embedding**: converte um inteiro positivo (subscrito) em um vetor de tamanho fixo, por exemplo, converte [[4],[20]] em [[0.25,0.1],[0.6,-0.2 ]]. A camada de embedding pode ser usada apenas como a primeira camada de modelo.
* **tf.keras.layers.Dropout**: constrói a camada dropout.

Os principais parâmetros de configuração de rede em tf.keras.layers incluem:

* **activation**: define a função de ativação de uma camada. Por padrão, o sistema não usa nenhuma função de ativação.
* **kernel_initializer e bias_initializer**: esquemas de inicialização que criam os pesos de uma camada (kernel e bias). O padrão é o inicializador uniforme Glorot.
* **kernel_regularizer e bias_regularizer**: esquemas de regularização que se aplicam aos pesos de uma camada (kernel e bias), por exemplo, regularização L1 ou L2. Por padrão, o sistema não usa funções de regularização.

### 2.2.1 Dense Layer

Os principais parâmetros de configuração em tf.keras.layers.Dense incluem:

* **units**: número de neurônios
* **activation**: função de ativação
* **use_bias**: se deve usar os termos de bias. São usados por padrão.
* **kernel_initializer**: esquema de inicialização que cria o peso de uma camada (kernel)
* **bias_initializer**: esquema de inicialização que cria o peso de uma camada (bias)
* **kernel_regularizer**: esquema de regularização que aplica o peso de uma camada (kernel)
* **bias_regularizer**: esquema de regularização que aplica o peso de uma camada (bias)
* **activity_regularizer**: item regular aplicado à saída, um objeto Regularizador
* **kernel_constraint**: restrição aplicada a um peso
* **bias_constraint**: restrição aplicada a um peso

In [4]:
'''
Crie uma camada totalmente conectada que contém 32 neurônios e defina a função de ativação para
sigmoide. O parâmetro de ativação pode ser definido como uma string de nome de função, por exemplo,
sigmoid, ou um objeto de função, i.e., tf.sigmoid.tf.keras.layers.Dense(32, activation='sigmoid')
'''
tf.keras.layers.Dense(32, activation=tf.sigmoid)
# Set kernel_initializer.
tf.keras.layers.Dense(32, kernel_initializer=tf.keras.initializers.he_normal)
# Set kernel_regularizer to the L2 regularization.
tf.keras.layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))

### 2.2.2 Conv2D Layer

Os principais parâmetros de configuração em tf.keras.layers.Conv2D incluem:

* **filters**: número de kernels de convolução (dimensões de saída)
* **kernel_size**: largura e comprimento de um kernel de convolução
* **strides**: passo de convolução
* **padding**: política de preenchimento zero. Quando o preenchimento é definido como válido, apenas a convolução válida é executada, ou seja, os dados de limite não são processados. Quando o preenchimento é definido como igual, o resultado da convolução no limite é reservado e, consequentemente, a forma de saída geralmente é a mesma que a forma de entrada.
* **activation**: função de ativação
* **data_format**: formato de dados. O valor pode ser canais_primeiro ou canais_último. Por exemplo, para uma imagem RGB de 128 x 128, os dados são organizados como (3,128,128) se o valor for canais_primeiro e como (128,128,3) se o valor for canais_último. O valor padrão deste parâmetro é o valor definido em ~/.keras/keras.json. Se o valor nunca foi definido, o valor padrão é channel_last.
* Outros parâmetros incluem use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraints e bias_constraints.

In [5]:
tf.keras.layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

### 2.2.3 MaxPooling2D e AveragePooling2D Layers

Os principais parâmetros de configuração em tf.keras.layers.MaxPooling2D/AveragePooling2D incluem:
* **pool_size**: tamanho do kernel agrupado. Por exemplo, se a matriz (2, 2) for usada, a imagem fica com metade do comprimento original em ambas as dimensões. Se esse parâmetro for definido como um número inteiro, o número inteiro será o valor de todas as dimensões.
* **strides**: valor do passo.
* Outros parâmetros incluem padding e data_format.

In [6]:
tf.keras.layers.MaxPooling2D(pool_size=(2,2),strides=(2,1))

### 2.2.4 LSTM e GRU Layers

Os principais parâmetros de configuração em tf.keras.layers.LSTM e tf.keras.layers.GRU incluem:

* **units**: dimensão de saída
* **input_shape** (timestep, input_dim): timestep pode ser definido como None e input_dim indica as dimensões dos dados de entrada.
* **activation**: função de ativação
* **recurrent_activation**: função de ativação a ser usada para a etapa recorrente
* **return_sequences**: Se o valor for True, todas as sequências são retornadas. Se o valor for Falso, a saída na última célula da sequência de saída será retornada.
* **return_state**: Valor booleano, indicando se deve retornar o último estado além da saída.
* **dropout**: flutua entre 0 e 1, fração dos neurônios a cair para a transformação linear das entradas
* **recurrent_dropout**: flutua entre 0 e 1, fração dos neurônios a cair para a transformação linear do estado recorrente

In [7]:
inputs       = tf.keras.Input(shape=(3, 1))
lstm         = tf.keras.layers.LSTM(1, return_sequences=True)(inputs)
model_lstm_1 = tf.keras.models.Model(inputs=inputs, outputs=lstm)
inputs       = tf.keras.Input(shape=(3, 1))

lstm         = tf.keras.layers.LSTM(1, return_sequences=False)(inputs)
model_lstm_2 = tf.keras.models.Model(inputs=inputs, outputs=lstm)

# Sequences t1, t2, and t3
data = [[[0.1],[0.2],[0.3]]]
print(data)
print("Saída quando return_sequences é definido como True\n",model_lstm_1.predict(data))
print("Saída quando return_sequences é definido como False\n",model_lstm_2.predict(data))

[[[0.1], [0.2], [0.3]]]
1/1 [==============================] - 1s 708ms/step
Saída quando return_sequences é definido como True
 [[[-0.01530277]
  [-0.0430234 ]
  [-0.07951193]]]
1/1 [==============================] - 1s 548ms/step
Saída quando return_sequences é definido como False
 [[-0.05740608]]


## 2.3 Compilando Modelos

Após a construção de um modelo, chame compile para configurar seu processo de aprendizagem:

compile( Optimizer='rmsprop', loss=None,metrics=None, loss_weights=None):
* **optimizer**: otimizador
* **loss**: função de perda, entropia cruzada para tarefas binárias e MSE para tarefas de regressão
* **metrics**: critérios de avaliação do modelo durante o treinamento e teste. Por exemplo, as métricas podem ser definidas como ['accuracy']. Para especificar vários critérios de avaliação, transfira um dicionário. Por exemplo, defina as métricas como {'output_a':'accuracy'}.
* **loss_weights**: Se o modelo tiver várias saídas de tarefa, você precisará especificar um peso para cada saída ao otimizar a perda global.

In [8]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer = tf.keras.optimizers.Adam(0.001),
              loss      = tf.keras.losses.categorical_crossentropy,
              metrics   = [tf.keras.metrics.categorical_accuracy])

## 2.4 Treinando Modelos

fit(x=None, y=None, batch_size=None, epochs=1, verbose=1, callbacks=None, validation_split=0.0, validation_data=None, shuffle=True, class_weight=None, sample_weight=None, initial_epoch=0, steps_per_epoch=None, validation_steps=None):

* **x**: dados de treinamento de entrada
* **y**: labels (rotulado)
* **batch_size**: número de amostras para cada atualização de gradiente. O valor padrão 32.
* **epochs**: número de rodadas de iteração do modelo de treinamento
* **verbose**: modo de exibição de log. O valor pode ser 0, 1 ou 2. 0 = sem exibição; 1 = barra de progresso; 2 = uma linha para cada rodada
* **callbacks**: função callback utilizada durante o treinamento
* **validação_split**: proporção do conjunto de dados de validação para os dados de treinamento
* **validação_data**: conjunto de dados de validação. Este parâmetro substitui validação_split.
* **shuffle**: se os dados devem ser embaralhados antes de cada rodada de iteração. Este parâmetro é inválido quando steps_per_epoch não é None.
* **initial_epoc**h: época em que se inicia o treino (útil para retomar um peso de treino anterior)
* **steps_per_epoch**: definido para o tamanho do conjunto de dados ou batch_size
* **valid_steps**: Número total de etapas (lotes de amostras) a serem validadas antes de parar. Este parâmetro é válido apenas quando steps_per_epoch é especificado.

In [9]:
import numpy as np

train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x   = np.random.random((200, 36))
val_y   = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 1s 34ms/step - loss: 12.3252 - categorical_accuracy: 0.1110 - val_loss: 12.1683 - val_categorical_accuracy: 0.0850
Epoch 2/10
10/10 [==============================] - 0s 8ms/step - loss: 12.3249 - categorical_accuracy: 0.1110 - val_loss: 12.1681 - val_categorical_accuracy: 0.0850
Epoch 3/10
10/10 [==============================] - 0s 8ms/step - loss: 12.3244 - categorical_accuracy: 0.1110 - val_loss: 12.1676 - val_categorical_accuracy: 0.0850
Epoch 4/10
10/10 [==============================] - 0s 8ms/step - loss: 12.3235 - categorical_accuracy: 0.1110 - val_loss: 12.1668 - val_categorical_accuracy: 0.0850
Epoch 5/10
10/10 [==============================] - 0s 8ms/step - loss: 12.3238 - categorical_accuracy: 0.1110 - val_loss: 12.1676 - val_categorical_accuracy: 0.0850
Epoch 6/10
10/10 [==============================] - 0s 6ms/step - loss: 12.3240 - categorical_accuracy: 0.1110 - val_loss: 12.1675 - val_categorical_accuracy: 0.0850
Epo

Para grandes conjuntos de dados, você pode usar tf.data para criar pipelines de entrada de treinamento.

In [10]:
dataset     = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset     = dataset.batch(32)
dataset     = dataset.repeat()

val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
validation_data=val_dataset, validation_steps=3)

Epoch 1/10
30/30 [==============================] - 1s 8ms/step - loss: 12.3422 - categorical_accuracy: 0.1083 - val_loss: 11.9880 - val_categorical_accuracy: 0.0625
Epoch 2/10
30/30 [==============================] - 0s 3ms/step - loss: 12.3048 - categorical_accuracy: 0.1100 - val_loss: 11.9845 - val_categorical_accuracy: 0.0625
Epoch 3/10
30/30 [==============================] - 0s 3ms/step - loss: 12.2976 - categorical_accuracy: 0.1154 - val_loss: 11.9810 - val_categorical_accuracy: 0.0729
Epoch 4/10
30/30 [==============================] - 0s 3ms/step - loss: 12.3399 - categorical_accuracy: 0.1143 - val_loss: 11.9775 - val_categorical_accuracy: 0.0729
Epoch 5/10
30/30 [==============================] - 0s 3ms/step - loss: 12.3017 - categorical_accuracy: 0.1111 - val_loss: 11.9739 - val_categorical_accuracy: 0.0729
Epoch 6/10
30/30 [==============================] - 0s 3ms/step - loss: 12.2947 - categorical_accuracy: 0.1100 - val_loss: 11.9709 - val_categorical_accuracy: 0.0729
Epoc

In [11]:
import os
# Set hyperparameters.
Epochs = 10
logdir=os.path.join("logs")
if not os.path.exists(logdir):
    os.mkdir(logdir)

# Defina uma função para definir dinamicamente a taxa de aprendizado.
def lr_Scheduler(epoch):
    if epoch > 0.9 * Epochs:
        lr = 0.0001
    elif epoch > 0.5 * Epochs:
        lr = 0.001
    elif epoch > 0.25 * Epochs:
        lr = 0.01
    else:
        lr = 0.1
    print(lr)
    return lr

callbacks = [
    # Early stopping:
    tf.keras.callbacks.EarlyStopping(
        # Métrica para determinar se o desempenho do modelo não tem mais melhorias
        monitor='val_loss',
        # Limiar para determinar se o desempenho do modelo não tem mais melhorias
        min_delta=1e-2,
        # Número de épocas em que o desempenho do modelo não tem mais melhorias
        patience=2),

        # Salva periodicamente os modelos.
        tf.keras.callbacks.ModelCheckpoint(
        # Path para o modelo
        filepath='testmodel_{epoch}.h5',
        # Determine se deseja salvar o modelo ideal.
        save_best_only=True,
        monitor='val_loss'),

        # Altere dinamicamente a taxa de aprendizado.
        tf.keras.callbacks.LearningRateScheduler(lr_Scheduler),
        # Usa o TensorBoard.
        tf.keras.callbacks.TensorBoard(log_dir=logdir)
]

model.fit(train_x, train_y, batch_size=16, epochs=Epochs,callbacks=callbacks, validation_data=(val_x, val_y))

0.1
Epoch 1/10
63/63 [==============================] - 1s 8ms/step - loss: 12.5231 - categorical_accuracy: 0.1010 - val_loss: 12.9611 - val_categorical_accuracy: 0.0900 - lr: 0.1000
0.1
Epoch 2/10
54/63 [========================>.....] - ETA: 0s - loss: 12.5874 - categorical_accuracy: 0.0961

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


63/63 [==============================] - 0s 4ms/step - loss: 12.6427 - categorical_accuracy: 0.0950 - val_loss: 12.3998 - val_categorical_accuracy: 0.1050 - lr: 0.1000
0.1
Epoch 3/10
63/63 [==============================] - 0s 5ms/step - loss: 12.7055 - categorical_accuracy: 0.0910 - val_loss: 11.8551 - val_categorical_accuracy: 0.0700 - lr: 0.1000
0.01
Epoch 4/10
63/63 [==============================] - 0s 4ms/step - loss: 12.1478 - categorical_accuracy: 0.1130 - val_loss: 12.0484 - val_categorical_accuracy: 0.0750 - lr: 0.0100
0.01
Epoch 5/10
63/63 [==============================] - 0s 4ms/step - loss: 12.2521 - categorical_accuracy: 0.1040 - val_loss: 12.0957 - val_categorical_accuracy: 0.0850 - lr: 0.0100


## 2.5 Avaliando Modelos

Funções de avaliação e predição: tf.keras.Model.evaluate e tf.keras.Model.predict.

In [12]:
test_x = np.random.random((1000, 36))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)

32/32 [==============================] - 0s 5ms/step - loss: 12.2270 - categorical_accuracy: 0.1060


[12.227045059204102, 0.10599999874830246]

In [13]:
pre_x  = np.random.random((10, 36))
result = model.predict(test_x,)
print(result)

32/32 [==============================] - 0s 2ms/step
[[0.15654925 0.05387461 0.1908797  ... 0.04772589 0.14686708 0.05014162]
 [0.10008267 0.03582852 0.30852103 ... 0.06411928 0.11899265 0.05177189]
 [0.07744738 0.05756279 0.13618182 ... 0.08610663 0.1785003  0.07001915]
 ...
 [0.10140043 0.02870186 0.12776817 ... 0.03025236 0.25050935 0.03824607]
 [0.13460673 0.02356885 0.12958837 ... 0.06448851 0.14120877 0.07327157]
 [0.12144029 0.06540425 0.09520619 ... 0.02747755 0.19558308 0.03749895]]


## 2.6 Salvando Modelos

In [14]:
import numpy as np

logdir='./model'
if not os.path.exists(logdir):
    os.mkdir(logdir)

model.save(logdir+'/the_save_model.h5')

new_model      = tf.keras.models.load_model(logdir+'/the_save_model.h5')
new_prediction = new_model.predict(test_x)

'''
np.testing.assert_allclose: determina se a similaridade de dois objetos excede a tolerância
especificada. Se sim, o sistema exibe uma exceção. atol: tolerância especificada
'''
np.testing.assert_allclose(result, new_prediction, atol=1e-6) # Prediction results are the same.

32/32 [==============================] - 0s 1ms/step


Depois que um modelo é salvo, você pode encontrar o arquivo de peso correspondente na pasta correspondente.

## 2.7 Salvando e Carregando pesos do Modelo
Se o nome do peso tiver o sufixo .h5 ou .keras, salve o peso como um arquivo HDF5; caso contrário, salve o peso como um arquivo de ponto de verificação do TensorFlow por padrão.

In [15]:
model.save_weights('./model/model_weights')
model.save_weights('./model/model_weights.h5')

# Carregar os pesos do modelo treinado
model.load_weights('./model/model_weights')
model.load_weights('./model/model_weights.h5')