<a href="https://colab.research.google.com/github/MarconeRafael/Modulos_Comuns_no_TensorFLow_2/blob/main/TensorFlow_Opera%C3%A7%C3%B5es_B%C3%A1sicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. TensorFlow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


# 1.1 Criação de Tensores

Métodos comuns para a criação de tensores incluem:
* **tf.constant()**: cria um tensor constante
* **tf.zeros(), tf.zeros_like(), tf.ones(), tf.ones_like()**: cria tensores constantes com valores zeros e uns respectivamente
* **tf.fill()**:cria um tensor com valores definidos pelo programador
* **tf.random()**: cria um tensor com uma distribuição conhecida
* **tf.convert_to_tensor()**: converte uma lista/ndarray para um tensor

### 1.1.1 tf.constant()

tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False):
* **value**: valores
* **dtype**: tipo dos dados
* **shape**: formato do tensor
* **name**: nome do tensor
* **verify_shape**: Booleano que permite a verificação do formato dos valores. O valor padrão é falso. Se Verify_shape for definido como True, o sistema verificará se a forma do valor é consistente com a forma. Se forem inconsistentes, um erro será relatado.

In [2]:
const_a = tf.constant([1, 2, 3, 4], shape=[2, 2], dtype=tf.float32)
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [3]:
print(f'Conteúdo do tensor const_a: {list(const_a.numpy())}')
print(f'Tipo dos dados do tensor const_a: {const_a.dtype}')
print(f'Formato do tensor const_a: {const_a.shape}')
print(f'Dispositivo que gerou const_a: {const_a.device}')

Conteúdo do tensor const_a: [array([1., 2.], dtype=float32), array([3., 4.], dtype=float32)]
Tipo dos dados do tensor const_a: <dtype: 'float32'>
Formato do tensor const_a: (2, 2)
Dispositivo que gerou const_a: /job:localhost/replica:0/task:0/device:CPU:0


### 1.1.2 tf.zeros(), tf.zeros_like(), tf.ones(),tf.ones_like()

O uso de tf.ones() e tf.ones_like() é semelhante ao de tf.zeros() e tf.zeros_like(). Portanto, a seguir é apresentadocomo usar tf.ones() e tf.ones_like(). Criando um tensor com todos os elementos definidos como zero.

tf.zeros(shape, dtype=tf.float32):
* **shape**: formato do tensor
* **dtype**: tipo dos dados

In [4]:
zeros_1 = tf.zeros(shape=[2, 3], dtype=tf.int32)
zeros_1


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

tf.zeros_like(input_tensor, dtype=None):
* **input_tensor**: tensor que será utilizado como base para criar do novo tensor no mesmo formato
* **dtype**: tipo dos dados

In [5]:
zeros_2 = tf.zeros_like(const_a)
zeros_2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### 1.1.3 tf.fill()

Cria um tensor e o preenche com valores específicos
tf.fill(dims, value, name=None):
* **dims**: formato do tensor
* **value**: valores para preecher o tensor


In [6]:
fill_c = tf.fill([3,3], 8)
fill_c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)>

### 1.1.4 tf.random()

Este módulo é usado para gerar um tensor com uma distribuição específica. Os métodos comuns neste módulo incluem tf.random.uniform(), tf.random.normal() e tf.random.shuffle(). A seguir apresentaremos como usar tf.random.normal().

Cria um tensor que esteja de acordo com a distribuição normal.

tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32,seed=None):
* **shape**: formato dos dados
* **mean**: valor da média para a distribuição gaussiana
* **stddev**: desvio padrão para a distribuição gaussiana
* **dtype**: tipo de dados
* **seed**: semente para geração dos dados


In [7]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1)
random_e

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)>

### 1.1.5 tf.convert_to_tensor()

tf.convert_to_tensor(value, dtype=None):
* **value**: value to be converted
* **dtype**: tensor data type

In [8]:
lista = [1, 2, 3, 4, 5]
type(lista)

list

In [9]:
tensor_f = tf.convert_to_tensor(lista, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

## 1.2 Criando Tensores Mútaveis

No TensorFlow, as variáveis são criadas e rastreadas por meio da classe tf.Variable. Um tf.Variable representa um tensor cujo valor pode ser alterado executando operações nele. Operações específicas permitem que você leia e modifique os valores desse tensor.

In [10]:
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
print("Valor de var_1: ",var_1.read_value())
var_value_1 = [[1,2,3], [4,5,6]]
var_1.assign(var_value_1)
print("Novo valor para var_1: ",var_1.read_value())

Valor de var_1:  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Novo valor para var_1:  tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [12]:
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

## 1.3 Indexando e Fatiando Tensores

### 1.3.1 Slicing

* **[start: end]**: extrai os dados entre o indices de **start** e **end** do tensor
* **[start :end :step]** ou **[::step]**: extrai os dados entre o indices de *start* e *end* do tensor com intervalos de tamanho **step**


In [13]:
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-7.06635833e-01, -1.92604470e+00,  4.57503915e-01],
         [-4.33816165e-01, -6.94335625e-02, -4.13806707e-01],
         [ 4.26806986e-01, -6.96643144e-02, -1.41220614e-01],
         ...,
         [ 8.26046392e-02, -1.14843643e+00, -1.26957476e+00],
         [ 4.59770918e-01, -1.34228647e+00,  7.52078891e-02],
         [ 2.35636681e-01, -5.20919621e-01, -3.55637431e+00]],

        [[ 5.51012993e-01,  5.72373979e-02,  1.73425630e-01],
         [ 1.19851637e+00, -8.55669200e-01,  9.26242054e-01],
         [-1.21824652e-01,  1.33737639e-01, -1.76894572e-02],
         ...,
         [-5.04699588e-01,  7.13584960e-01,  5.15836418e-01],
         [-7.68173456e-01,  4.63459551e-01,  1.32277203e+00],
         [ 1.44649434e+00, -2.75917441e-01,  8.34762990e-01]],

        [[-7.94877291e-01,  2.62309492e-01, -9.50751245e-01],
         [ 8.19095731e-01,  1.84470010e+00,  1.35963893e+00],
         [-1.14093924e+00,  2.11972624e-01

In [14]:
tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-0.70663583, -1.9260447 ,  0.4575039 ],
        [-0.43381616, -0.06943356, -0.4138067 ],
        [ 0.426807  , -0.06966431, -0.14122061],
        ...,
        [ 0.08260464, -1.1484364 , -1.2695748 ],
        [ 0.45977092, -1.3422865 ,  0.07520789],
        [ 0.23563668, -0.5209196 , -3.5563743 ]],

       [[ 0.551013  ,  0.0572374 ,  0.17342563],
        [ 1.1985164 , -0.8556692 ,  0.92624205],
        [-0.12182465,  0.13373764, -0.01768946],
        ...,
        [-0.5046996 ,  0.71358496,  0.5158364 ],
        [-0.76817346,  0.46345955,  1.322772  ],
        [ 1.4464943 , -0.27591744,  0.834763  ]],

       [[-0.7948773 ,  0.2623095 , -0.95075125],
        [ 0.81909573,  1.8447001 ,  1.3596389 ],
        [-1.1409392 ,  0.21197262,  0.77918375],
        ...,
        [-0.3973458 , -0.02520764, -0.89375705],
        [ 1.0260229 ,  0.76497006, -0.20477214],
        [ 0.66195476, -0.16537987,  0.16486755]],

       ...,

     

In [15]:
# Extract one slice every two images.
tensor_h[::2,...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[-7.06635833e-01, -1.92604470e+00,  4.57503915e-01],
         [-4.33816165e-01, -6.94335625e-02, -4.13806707e-01],
         [ 4.26806986e-01, -6.96643144e-02, -1.41220614e-01],
         ...,
         [ 8.26046392e-02, -1.14843643e+00, -1.26957476e+00],
         [ 4.59770918e-01, -1.34228647e+00,  7.52078891e-02],
         [ 2.35636681e-01, -5.20919621e-01, -3.55637431e+00]],

        [[ 5.51012993e-01,  5.72373979e-02,  1.73425630e-01],
         [ 1.19851637e+00, -8.55669200e-01,  9.26242054e-01],
         [-1.21824652e-01,  1.33737639e-01, -1.76894572e-02],
         ...,
         [-5.04699588e-01,  7.13584960e-01,  5.15836418e-01],
         [-7.68173456e-01,  4.63459551e-01,  1.32277203e+00],
         [ 1.44649434e+00, -2.75917441e-01,  8.34762990e-01]],

        [[-7.94877291e-01,  2.62309492e-01, -9.50751245e-01],
         [ 8.19095731e-01,  1.84470010e+00,  1.35963893e+00],
         [-1.14093924e+00,  2.11972624e-01

### 1.3.2 Indexando

O formato básico de um índice é a[d1][d2][d3].

In [16]:
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.4914031>

Se os índices a serem extraídos não forem consecutivos, tf.gather e tf.gather_nd são comumente usados para extração de dados no TensorFlow. Para extrair dados de uma dimensão específica, podemos usar:

tf.gather(params, indices, axis=None)
* **params**: tensor de entrada
* **indices**: indice dos dados a serem extraídos
* **axis**: dimensão na qual serão extraída os dados

In [17]:
indices = [0,1,3]
tf.gather(tensor_h,axis=0,indices=indices)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[-0.70663583, -1.9260447 ,  0.4575039 ],
         [-0.43381616, -0.06943356, -0.4138067 ],
         [ 0.426807  , -0.06966431, -0.14122061],
         ...,
         [ 0.08260464, -1.1484364 , -1.2695748 ],
         [ 0.45977092, -1.3422865 ,  0.07520789],
         [ 0.23563668, -0.5209196 , -3.5563743 ]],

        [[ 0.551013  ,  0.0572374 ,  0.17342563],
         [ 1.1985164 , -0.8556692 ,  0.92624205],
         [-0.12182465,  0.13373764, -0.01768946],
         ...,
         [-0.5046996 ,  0.71358496,  0.5158364 ],
         [-0.76817346,  0.46345955,  1.322772  ],
         [ 1.4464943 , -0.27591744,  0.834763  ]],

        [[-0.7948773 ,  0.2623095 , -0.95075125],
         [ 0.81909573,  1.8447001 ,  1.3596389 ],
         [-1.1409392 ,  0.21197262,  0.77918375],
         ...,
         [-0.3973458 , -0.02520764, -0.89375705],
         [ 1.0260229 ,  0.76497006, -0.20477214],
         [ 0.66195476, -0.16537987,  0.1648675

tf.gather_nd permite extrair os dados de múltiplas dimensões

tf.gather_nd(params, indices):
* **params**: tensor de entrada
* **indices**: indices dos dados a serem extraídos. Geralmente, é uma lista multi-dimensional.

In [18]:
indices = [[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_h,indices=indices)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1.1985164 , -0.57992595], dtype=float32)>

## 1.4 Alterando Dimensões dos Tensores

In [19]:
const_d_1 = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32)

# três formas para verificar as dimensões do tensor
print(const_d_1.shape)
print(const_d_1.get_shape())
print(tf.shape(const_d_1))


(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


Conforme descrito acima, **.shape** e **.get_shape()** retornam objetos TensorShape, enquanto **tf.shape(x)** retorna objetos Tensor.

### 1.4.1 Reshaping
tf.reshape(tensor,shape,name=None):
* **tensor**: tensor de entrada
* **shape**: formato para ser alterado

In [20]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### 1.4.2 Expandindo Dimensões

tf.expand_dims(input,axis,name=None):
* **input**: tensor de entrada
* **axis**: adiciona uma dimensão após a dimensão do eixo. Dada uma entrada de dimensões D, o eixo deve estar no intervalo [-(D+1), D] (inclusive). Um valor negativo indica a ordem inversa.

In [21]:
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("Tamanho original dos dados: ",expand_sample_1.shape)
print("add uma dimensão (axis=0) antes da primeira dimensão: ",tf.expand_dims(expand_sample_1, axis=0).shape)
print("add uma dimensão (axis=1) antes da segunda dimensão: ",tf.expand_dims(expand_sample_1, axis=1).shape)
print("add uma dimensão (axis=-1) depois da úçtima dimensão: ",tf.expand_dims(expand_sample_1, axis=-1).shape)

Tamanho original dos dados:  (100, 100, 3)
add uma dimensão (axis=0) antes da primeira dimensão:  (1, 100, 100, 3)
add uma dimensão (axis=1) antes da segunda dimensão:  (100, 1, 100, 3)
add uma dimensão (axis=-1) depois da úçtima dimensão:  (100, 100, 3, 1)


### 1.4.3 Reduzindo dimensões
tf.squeeze(input,axis=None,name=None):

Este método é usado para remover dimensões de tamanho 1 da forma de um tensor.
* **entrada**: tensor de entrada
* **eixo**: Se você não deseja remover todas as dimensões de tamanho 1, remova as dimensões específicas de tamanho 1 especificando o eixo.

In [22]:
orig_sample_1 = tf.random.normal([1,100,100,3])
print("Tamanho original dos dados: ",orig_sample_1.shape)

squeezed_sample_1 = tf.squeeze(orig_sample_1)
print("Dados reduzidos: ",squeezed_sample_1.shape)

# As dimensões da amostra reduzida são: [1, 2, 1, 3, 1, 1].
squeeze_sample_2 = tf.random.normal([1, 2, 1, 3, 1, 1])
t_1 = tf.squeeze(squeeze_sample_2) # dimensões de tamanho 1 são removidas.
print('t_1.shape:', t_1.shape)

# Remove uma dimensão especifica
# 't' é um tensor de shape [1, 2, 1, 3, 1, 1]
t_1_new = tf.squeeze(squeeze_sample_2, [2, 4])
print('t_1_new.shape:', t_1_new.shape)

Tamanho original dos dados:  (1, 100, 100, 3)
Dados reduzidos:  (100, 100, 3)
t_1.shape: (2, 3)
t_1_new.shape: (1, 2, 3, 1)


### 1.4.4 Transpose

tf.transpose(a,perm=None,conjugate=False,name='transpose'):
* **a**: tensor de entrada
* **perm**: permutação das dimensões de a, geralmente usada para transpor matrizes de alta dimensão
* **conjugate**: transposição conjugada


In [23]:
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("Tamanho original dos dados: ",trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("Dados transpostos: ",transposed_sample_1.shape)

Tamanho original dos dados:  (2, 3)
Dados transpostos:  (3, 2)


O parâmetro perm é necessário para transpor dados de alta dimensão. perm indica a permutação das dimensões do tensor de entrada.
Para um tensor tridimensional, sua permutação de dimensão original é [0, 1, 2] (perm), indicando o comprimento, a largura e a altura dos dados de alta dimensão, respectivamente. Ao alterar a sequência de valores em perm, você pode transpor a dimensão correspondente dos dados.

In [41]:
trans_sample_2 = tf.random.normal([4,100,200,3])
print("original data size: ",trans_sample_2.shape)
transposed_sample_2 = tf.transpose(trans_sample_2,[0,2,1,3])
print("transposed data size: ",transposed_sample_2.shape)

original data size:  (4, 100, 200, 3)
transposed data size:  (4, 200, 100, 3)


### 1.4.5 Broadcasting

Broadcasting é usado para transmitir dados de uma dimensão baixa para uma dimensão alta.

tf.broadcast_to(input,shape,name=None):
* **input**: tensor de entrada
* **shape**: formato do novo tensor

In [24]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data: ",broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print("broadcast data: ",broadcasted_sample_1.numpy())

original data:  [1 2 3 4 5 6]
broadcast data:  [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [25]:
a = tf.constant([[ 0, 0, 0],
                [10,10,10],
                [20,20,20],
                [30,30,30]])

b = tf.constant([1,2,3])
print(a + b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


## 1.5 Operações Aritiméticas

As operações aritméticas incluem adição (tf.add), subtração (tf.subtract), multiplicação (tf.multiply), divisão (tf.divide), logaritmo (tf.math.log) e potências (tf.pow). O seguinte é um exemplo de adição.

In [26]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

tf.Tensor(
[[ 4 11]
 [ 6 17]], shape=(2, 2), dtype=int32)


### 1.5.1 Multiplicação de Matrizes

A multiplicação de matrizes é implementada chamando tf.matmul.

In [27]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]], dtype=int32)>

### 1.5.2 Coletando Estatísticas sobre os Tensores
Os métodos para coletar estatísticas de tensores incluem:

* **tf.reduce_min/max/mean()**: calcula o valor mínimo, máximo e médio do tensor.
* **tf.argmax()/tf.argmin()**: calcula a posição do valor mínimo e máximo no tensor.
* **tf.equal()**: verifica se dois tensores possuem os mesmos valores
* **tf.unique()**: removes duplicate elements from a tensor.
* **tf.nn.in_top_k(prediction, target, K)**: calculates whether the predicted value is equal to the actual value and returns a tensor of the Boolean type.

In [28]:
argmax_sample_1 = tf.constant([[1,3,2], [2, 5, 8], [7, 5, 9]])
print(f'Tensor de entrada: \n{argmax_sample_1.numpy()}')

max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)

print(f'Maior valor por coluna: {max_sample_1.numpy()}')
print(f'Maior valor por linha : {max_sample_2.numpy()}')

Tensor de entrada: 
[[1 3 2]
 [2 5 8]
 [7 5 9]]
Maior valor por coluna: [2 1 2]
Maior valor por linha : [1 2 2]


### 1.5.3 Operações baseadas em Dimensões

No TensorFlow, operações como **tf.reduce_\*** reduzem as dimensões do tensor. Essas operações podem ser realizadas nos elementos de dimensão de um tensor, por exemplo, calculando o valor médio por linha e calculando um produto de todos os elementos do tensor.

Operações comuns incluem **tf.reduce_sum (adição)**, **tf.reduce_prod (multiplicação)**, **tf.reduce_min (mínimo)**, **tf.reduce_max (máximo)**, **tf.reduce_mean (média)**, **tf.reduce_all (AND lógico)**, **tf.reduce_any ( OR lógico)** e **tf.reduce_logsumexp (log(sum(exp)))**. A forma de uso dessas operações são semelhantes. Portanto, o exemplo a seguir usa a operação tf.reduce_sum como base

Calcule a soma dos elementos nas dimensões de um tensor.

tf.reduce_sum(input_tensor, axis=None, keepdims=False):
* **input_tensor**: tensor para reduzir
* **axis**: eixo a ser calculado. Se este parâmetro não for especificado, o valor médio de todos os elementos é calculado.
* **keepdims**: se deve reduzir a dimensão. Se este parâmetro for definido como True, o resultado da saída retém a forma do tensor de entrada. Se este parâmetro for definido como Falso, a dimensão do resultado da saída é reduzido.

In [29]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("Dados originais", reduce_sample_1.numpy())
print("Calcula a soma de todos os elementos em um tensor (axis=None):",tf.reduce_sum(reduce_sample_1,axis=None).numpy())
print("Calcula a soma de todos os elementos por coluna (axis=0): ",tf.reduce_sum(reduce_sample_1,axis=0).numpy())
print("Calcula a soma de todos os elementos por linha (axis=1): ",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

Dados originais [[1 2 3]
 [4 5 6]]
Calcula a soma de todos os elementos em um tensor (axis=None): 21
Calcula a soma de todos os elementos por coluna (axis=0):  [5 7 9]
Calcula a soma de todos os elementos por linha (axis=1):  [ 6 15]


### 1.5.4 Concatenando Tensores

No TensorFlow, as operações de concatenação de tensor incluem:
* **tf.contact()**: concatena tensores ao longo de uma dimensão. As outras dimensões permanecem inalteradas.
* **tf.stack()**: empilha a lista de tensores de rank R em um tensor de rank (R+1). As dimensões são alteradas após o empilhamento.

**tf.concat(values, axis):**
* **values**: tensor de entrada
* **axis**: dimensão na qual será concatenada

In [30]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("Formato dos dados originais: ",concat_sample_1.shape, concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("Formato dos dados concatenados: ",concated_sample_1.shape)

Formato dos dados originais:  (4, 100, 100, 3) (40, 100, 100, 3)
Formato dos dados concatenados:  (44, 100, 100, 3)


Uma dimensão é adicionada a uma matriz original da mesma maneira. axis determina a posição onde a dimensão é adicionada.

**tf.stack(values, axis=0):**
* **values**: lista de tensores com o mesmo formato e tipo
* **axis**: eixo para empilhar os tensores

In [31]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("Formato dos dados originais: ",stack_sample_1.shape, stack_sample_2.shape)

stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("Formato dos dados stackados: ",stacked_sample_1.shape)

Formato dos dados originais:  (100, 100, 3) (100, 100, 3)
Formato dos dados stackados:  (2, 100, 100, 3)


### 1.5.5 Separando Tensores

No TensorFlow, as operações de separação do tensor incluem:
* **tf.unstack()**: descompacta os tensores ao longo da dimensão específica.
* **tf.split()**: divide um tensor em uma lista de subtensores com base em dimensões específicas.

tf.unstack(value,num=None,axis=0):
* **value**: tensor de entrada
* **num**: exibe uma lista contendo num elementos. num deve ser igual ao número de elementos na dimensão especificada. Geralmente, esse parâmetro é ignorado.
* **axis**: eixo para desempilhar

In [32]:
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[ 2.2624941e+00,  1.2447733e+00,  3.5410070e-01],
         [ 4.5642045e-01, -5.0833714e-01, -9.7257525e-01],
         [-1.7199630e+00, -9.3757111e-01,  7.2959274e-01],
         ...,
         [-2.8627160e-01,  3.6713687e-01,  5.6217277e-01],
         [ 1.0710719e+00, -3.3370182e-01, -8.3276939e-01],
         [-9.1812134e-01, -4.3923119e-01,  6.9818813e-01]],
 
        [[ 4.2792284e-01,  5.9350532e-01,  6.7192197e-02],
         [ 4.7006398e-01, -1.7924404e-01,  2.7644235e-01],
         [ 1.3621633e+00, -1.0663546e+00, -5.3726262e-01],
         ...,
         [-1.7050306e+00,  3.1857282e-01, -1.6540185e-01],
         [-1.7737105e+00,  9.5042783e-01,  5.2818120e-03],
         [-5.9803927e-01,  1.2550112e+00, -1.9964716e+00]],
 
        [[-9.3000537e-01,  7.2642900e-02,  6.5151155e-02],
         [-1.3598039e+00,  9.8733789e-01,  1.4837321e+00],
         [ 3.1177187e-01, -2.3209550e+00,  2.3227017e-01],
         ...,
         [ 

tf.split(value, num_or_size_splits, axis=0):
* **value**: tensor de entrada
* **num_or_size_splits**: número de divisões
* **axis**: dimensão ao longo da qual dividir

In [33]:
import numpy as np

split_sample_1 = tf.random.normal([10,100,100,3])
print("Formato dos dados originais: ",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)

print("Formato dos dados separados com num=5: ",np.shape(splited_sample_1))

splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("Formato dos dados separados com num=[3,5,2]:",
np.shape(splited_sample_2[0]),
np.shape(splited_sample_2[1]),
np.shape(splited_sample_2[2]))

Formato dos dados originais:  (10, 100, 100, 3)
Formato dos dados separados com num=5:  (5, 2, 100, 100, 3)
Formato dos dados separados com num=[3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


### 1.5.6 Ordenando Tensores
No TensorFlow, as operações de ordenação de tensores incluem:
* **tf.sort()**: ordena os tensores em ordem crescente ou decrescente e retorna os tensores ordenados.
* **tf.argsort()**: ordena os tensores em ordem crescente ou decrescente e retorna os índices.
* **tf.nn.top_k()**: retorna os k maiores valores.

tf.sort/argsort(input, direction, axis):
* **input**: tensor de entrada
* **direction**: direção na qual ordenar os valores. O valor pode ser DESCENDENTE ou ASCENDENTE. O valor padrão é ASCENDENTE (do menor para o maior).
* **axis**: eixo ao longo do qual será ordenado. O valor padrão é -1, que ordena o último eixo.

In [34]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor: ",sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor ordenado de forma ascendente: ",sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("Indices doselementos em ordem ascendente: ",sorted_sample_2.numpy())

input tensor:  [0 2 1 5 8 9 6 4 3 7]
tensor ordenado de forma ascendente:  [0 1 2 3 4 5 6 7 8 9]
Indices doselementos em ordem ascendente:  [0 2 1 8 7 3 6 9 4 5]


tf.nn.top_k(input,K,sorted=TRUE):
* **input**: tensor de entrada
* **K**: k maiores valores a serem produzidos e seus índices
* **sorted**: sorted=TRUE indica em ordem crescente. sorted=FALSE indica em ordem decrescente.

Dois tensores são retornados:
* **valores**: k maiores valores em cada linha
* **índices**: índices de valores dentro da última dimensão de entrada

In [35]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor: ",sort_sample_1.numpy())
print("K maiores valores em ordem ascendente: ", values.numpy())
print("indices dos K maiores valores em ordem ascendente: ", index.numpy())

input tensor:  [0 2 1 5 8 9 6 4 3 7]
K maiores valores em ordem ascendente:  [9 8 7 6 5]
indices dos K maiores valores em ordem ascendente:  [5 4 9 6 3]


## 1.6 Modo de Execução

**Eager**:
O modo de execução ansioso do TensorFlow é um tipo de programação imperativa, que é a mesma do Python nativo. Quando você executa uma determinada operação, o sistema retorna imediatamente um resultado.

**Graph**:
O TensorFlow 1 adota o modo de grafo para primeiro construir um grafo computacional, habilitar uma sessão e, em seguida, alimentar os dados reais para obter um resultado.

No modo de execução **Eager**, a depuração do código é mais fácil, mas a eficiência da execução do código é menor. O código a seguir implementa a multiplicação simples usando o TensorFlow para comparar as diferenças entre o modo de execução antecipado e o modo gráfico.

In [36]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2], [3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


### 1.6.1 Modo Tensorflow 1.x - Grafo Estático

In [37]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()


a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2],[3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)

with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


### 1.6.2 Modo Tensorflow 2 - Modo Eager

Reinicie o kernel para restaurar o TensorFlow para a versão 2 e habilitar o modo de execução **Eager**. Outra vantagem deste modo está na disponibilidade de funções nativas do Python, como a seguinte declaração de condição:

In [46]:
import tensorflow as tf
thre_1 = tf.random.uniform([], 0, 1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)

if thre_1.numpy() > 0.5:
    y = tf.matmul(x, x)
else:
    y = tf.add(x, x)

Tensor("random_uniform_5/RandomUniform:0", shape=(), dtype=float32)


AttributeError: ignored

Com o modo de execução **Eager**, esse fluxo de controle dinâmico pode gerar um valor NumPy extraível por um tensor, sem usar operadores como tf.cond e tf.while fornecidos no modo de **grafo**.

## 1.7 AutoGraph

Quando usado para comentar uma função, o decorador **tf.function** pode ser chamado como qualquer outra função. tf.function será compilado em um grafo, para que possa ser executado com mais eficiência em uma GPU ou TPU. Nesse caso, a função se torna uma operação no TensorFlow. A função pode ser chamada diretamente para gerar um valor de retorno. No entanto, a função é executada no modo de grafo e os valores das variáveis intermediárias não podem ser visualizados diretamente.

In [43]:
@tf.function
def simple_nn_layer(w,x,b):
    print(b)
    return tf.nn.relu(tf.matmul(w, x)+b)

In [44]:
w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor 'PartitionedCall:0' shape=(3, 3) dtype=float32>

De acordo com o resultado de saída, o valor de b na função não pode ser visualizado diretamente, mas o valor de retorno pode ser visualizado usando .numpy().

A seguir, comparamos o desempenho do gráfico e os modos de execução **Eager** executando a mesma operação (computação LSTM de uma camada).

In [45]:
# Use the timeit module to measure the execution time of a small code segment.
import timeit

# Criando uma camada convulucional CNN
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))

# Usamos @tf.function para converter a operação em um grafo estático
@tf.function
def CNN_fn(image):
    return CNN_cell(image)

image = tf.zeros([100, 200, 200, 3])

# Comparando os dois modos de execução
CNN_cell(image)
CNN_fn(image)

# Usamos timeit.timeit para mensurar o tempo de execução do código por 10 vezes
print("Tempo CNN execução em modo Eager:", timeit.timeit(lambda: CNN_cell(image), number=10))
print("Tempo CNN execução em modo Grafo:", timeit.timeit(lambda: CNN_fn(image), number=10))

Tempo CNN execução em modo Eager: 0.031986316000001125
Tempo CNN execução em modo Grafo: 0.014621519999991506
